server:
  port: 8080
  contextPath: /
  request:
    maxBodySize: 2048mb
    maxHeaderSize: 20mb
  session:
    timeout: 7200
    state:
      jwt:
        name: TOKEN #变量名；（可不配，默认：TOKEN）
        secret: "q7kuLQcrgAHEJ7XBpATQd5AL5+HVkWRxKnLhnsiSft0=" #密钥（使用 JwtUtils.createKey() 生成）；
        #prefix: Bearer #令牌前缀（可不配，默认：空）
        allowExpire: true #充许超时；（可不配，默认：true）；false，则token一直有效
        allowAutoIssue: false #充许自动输出；（可不配，默认：true）；flase，则不向header 或 cookie 设置值（由用户手动控制）
        allowUseHeader: true #充许使用Header传递；（可不配，默认：使用 Cookie 传递）；true，则使用 header 传递



solon:
#  debug: 1
  app:
    name: apisix-web
  view:
    mapping:
      html: FreemarkerRender
  logging:
    logger:
      "io.undertow":
        level: "WARN"
    appender:
      console:
        level: INFO
      file:
        level: INFO
        maxFileSize: "1 MB"
        maxHistory: "7"

#test:
#  db1:
#    jdbcUrl: jdbc:h2:file:~/tmp/h2;DB_CLOSE_DELAY=1000;DB_CLOSE_ON_EXIT=FALSE
#    #jdbcUrl: jdbc:h2:mem:test_mem
#    driverClassName: "org.h2.Driver"
#    username: "sa"
#    password: ""

spring:
  database:
    type: h2
  datasource:
    url:
    username:
    password:

#  db2:
#    schema: rock
#    jdbcUrl: jdbc:mysql://127.0.0.1:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
#    driverClassName: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#  db3:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://127.0.0.1:5432/rock?&ssl=false
#    username: rock
#    password: rock



